# Generated by Django 5.2.6 on 2025-12-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilebe',
            name='development_score',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='profilede',
            name='design_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='profilefe',
            name='development_score',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='profilepm',
            name='design_understanding',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='profilepm',
            name='development_understanding',
            field=models.FloatField(null=True),
        ),
    ]
