# Generated by Django 5.2.6 on 2025-12-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agreeableness',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='conscientiousness',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='extraversion',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='neuroticism',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='openness',
            field=models.IntegerField(null=True),
        ),
    ]
