# Generated by Django 5.2.6 on 2025-12-15 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matchings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='participant',
            field=models.ForeignKey(db_column='participant_id', on_delete=django.db.models.deletion.CASCADE, to='matchings.participant'),
        ),
        migrations.AddField(
            model_name='result',
            name='room',
            field=models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='matchings.room'),
        ),
        migrations.AddField(
            model_name='participant',
            name='room',
            field=models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='matchings.room'),
        ),
        migrations.AddField(
            model_name='team',
            name='result',
            field=models.ForeignKey(db_column='result_id', on_delete=django.db.models.deletion.CASCADE, to='matchings.result'),
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, to='matchings.team'),
        ),
        migrations.AddField(
            model_name='wagging',
            name='waggee',
            field=models.ForeignKey(db_column='waggee_id', on_delete=django.db.models.deletion.CASCADE, related_name='who_wagging_me', to='matchings.participant'),
        ),
        migrations.AddField(
            model_name='wagging',
            name='wagger',
            field=models.ForeignKey(db_column='wagger_id', on_delete=django.db.models.deletion.CASCADE, related_name='my_wagging_list', to='matchings.participant'),
        ),
    ]
