# Generated by Django 5.2.6 on 2025-11-10 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matchings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='participant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchings.participant'),
        ),
        migrations.AddField(
            model_name='result',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchings.room'),
        ),
        migrations.AddField(
            model_name='participant',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchings.room'),
        ),
        migrations.AddField(
            model_name='team',
            name='result_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchings.result'),
        ),
        migrations.AddField(
            model_name='member',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchings.team'),
        ),
        migrations.AddField(
            model_name='wagging',
            name='waggee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_wagging_me', to='matchings.participant'),
        ),
        migrations.AddField(
            model_name='wagging',
            name='wagger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_wagging_list', to='matchings.participant'),
        ),
    ]
