# Generated by Django 5.2.6 on 2025-12-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='agreeableness',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='conscientiousness',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='extraversion',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='neuroticism',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='openness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='active_hours',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='meeting_preference',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='part',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[('ADMIN', '운영진'), ('PARTICIPANT', '참가자')], default='PARTICIPANT', max_length=20),
        ),
        migrations.AlterField(
            model_name='participant',
            name='team_vibe',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('PENDING', '대기'), ('WAGGING', '꼬리 흔들기'), ('MATCHING', '매칭'), ('COMPLETED', '완료'), ('CLOSED', '닫힘')], default='PENDING', max_length=30),
        ),
    ]
