# Generated by Django 5.2.6 on 2025-12-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='agreeableness',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='conscientiousness',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='extraversion',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='neuroticism',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='openness',
            field=models.FloatField(null=True),
        ),
    ]
