# Generated by Django 5.2.6 on 2025-12-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='team_vibe',
            field=models.CharField(max_length=20),
        ),
    ]
