# Generated by Django 5.2.6 on 2025-12-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchings', '0003_alter_participant_team_vibe'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rematch_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(max_length=20),
        ),
    ]
